/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
//import java.net.MalformedURLException;
import java.io.IOException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
        // TestCases tests = new TestCases(); // Initialize your test class
        Redbus_bus bus = new Redbus_bus();

        //TODO: call your test case functions one after other here

        // tests.testCase01();
        bus.clickbus();
		bus.getsource();
		bus.getdestiny();
		bus.getyrandmonth("Sep 2023");
		bus.getdate("30");
		bus.searchclick();
		bus.businfo();
		bus.takescreenshot();

        //END Tests
        bus.endTest();

        // tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
